Repository gachi-mandoo-shell/kimchi-mandoo-shell, pull requests merged in 2021-05, with the labels that each got.

#53 Feat/prompt
  Makefile
  include/cursor.h
  include/minishell.h
  include/minishell_type.h
  include/parse.h
  include/parse_util.h
  include/util.h
  lib/libft/Makefile
  lib/libft/include/ft_string.h
  lib/libft/src/string/ft_strappendc.c
  src/cursor/cursor_left.c
  src/cursor/cursor_right.c
  src/cursor/delete_char.c
  src/cursor/delete_line.c
  src/cursor/putchar_tc.c
  src/exit_minshell.c
  src/init.c
  src/minishell.c
  src/parse/free_AST.c
  src/parse/lexical_analyzer.c
  src/parse/parse_line.c
  src/parse/parse_util.c
  src/parse/print_AST.c
  src/parse/syntax_analyzer.c
  src/parse/tokenizer.c
  src/util/get_line.c
  src/util/getch.c
  src/util/handle_history.c
  src/util/handle_key_input.c
  src/util/is_util.c
  src/util/print_PS1.c
Labels: enhancement

#59 feat: add parse_cmd, normalize
  include/minishell.h
  include/parse.h
  include/parse_util.h
  src/parse/normalize.c
  src/parse/parse_cmd.c
  src/parse/print_AST.c
Labels: enhancement, parse

#61 fix: ASTs memory leaks
  src/minishell.c
Labels: bug, fix

#64 feat: add ctrl+v(paste)
  src/util/getch.c
Labels: enhancement

#70 fix: normalize tokenizer
  src/parse/normalize.c
  src/parse/tokenizer.c
Labels: enhancement

#72 add parse_arg, wildcard search!!
  include/parse.h
  include/parse_util.h
  src/parse/is_wildcard.c
  src/parse/parse_arg.c
  src/parse/print_AST.c
  src_bonus/parse/parse_arg_bonus.c
Labels: enhancement

#83 export sort complete && unset (env의 마지막 노드 지울때 segfault) 해결
  include/builtin.h
  include/exec.h
  src/builtin/export_sort.c
  src/builtin/ft_export.c
  src/builtin/ft_unset.c
  src/envp/remove_envp.c
  src/exec/exec_cmd.c
  src/exec/fork.c
  src/exec/free_exec.c
  src/minishell.c
Labels: fix

#84 feat: add HEREDOC
  include/exec.h
  include/minishell.h
  include/minishell_type.h
  include/util.h
  src/exec/heredoc.c
  src/exec/parse_t_cmd.c
  src/exec/redirection.c
  src/minishell.c
  src/parse/is_wildcard.c
  src/parse/normalize.c
  src/parse/print_AST.c
  src/util/get_line.c
  src/util/getch.c
  src/util/handle_history.c
  src/util/handle_key_input.c
  src/util/handle_signal.c
  src/util/is_util.c
  src/util/print_PS.c
  src/util/print_PS2.c
Labels: enhancement

#85 fix: export error fix
  src/builtin/export_sort.c
  src/builtin/ft_export.c
  src/minishell.c
Labels: bug

#86 다중파이프시 redir_in 오류 && 다중 파이프 오류 조건 수정
  Makefile
  include/builtin.h
  include/exec.h
  src/builtin/export_sort.c
  src/builtin/ft_cd.c
  src/builtin/ft_env.c
  src/builtin/ft_exit.c
  src/builtin/ft_export.c
  src/builtin/ft_pwd.c
  src/builtin/ft_unset.c
  src/exec/builtin_parser.c
  src/exec/fork.c
  src/exec/ft_cmd.c
  src/exec/ft_error.c
  src/exec/make_cmd.c
  src/exec/parse_t_cmd.c
  src/exec/pipe.c
  src/exec/redirection.c
  src/parse/print_AST.c
Labels: fix

#89 fix: exec_cmd parse error handling!
  .vscode/settings.json
  .vscode/tasks.json
  include/exec.h
  include_bonus/exec_bonus.h
  src/exec/free_exec.c
  src_bonus/exec/free_exec_bonus.c
  src_bonus/exec/parse_t_cmd_bonus.c
Labels: bug
