Repository gachi-mandoo-shell/kimchi-mandoo-shell, pull requests merged in 2021-04, with the labels that each got.

#4 make_re flow_chart #1
  docs/flow_chart.drawio.svg
Labels: documentation

#5 update docs/flow_chart.drawio.svg
  docs/flow_chart.drawio.svg
Labels: documentation

#10 add typedef header file
  include/minishell.h
  include/minishell_type.h
Labels: documentation

#15 update github action workflow
  .github/workflows/build.yml
  .github/workflows/norm.yml
  .github/workflows/test.yml
  readme.md
Labels: enhancement

#19 style: add commit_template
  COMMIT_TEMPLATE.txt
Labels: documentation

#21 make init_envp function
  src/minishell.c
Labels: documentation

#27 refactor: prototype, typedef
  include/exec.h
  include/parse.h
  src/exec/exec.c
  src/minishell.c
  src/parse/parse.c
Labels: enhancement

#28 refactor: redefine strucre
  include/minishell_type.h
Labels: enhancement

#29 refactor: remove parse_args, update t_cmd
  include/minishell_type.h
  include/parse.h
Labels: enhancement

#38 libft 함수 추가
  Makefile
  lib/libft/Makefile
  lib/libft/include/ft_lst.h
  lib/libft/include/ft_memory.h
  lib/libft/include/ft_string.h
  lib/libft/src/lst/ft_lst_to_array.c
  lib/libft/src/memory/ft_free.c
  lib/libft/src/memory/ft_free_ret.c
  lib/libft/src/string/ft_strndup_move.c
Labels: enhancement

#43 feat: update ft_malloc
  lib/libft/src/memory/ft_malloc.c
Labels: enhancement

#44 chore: add vscode debuger setup
  .vscode/launch.json
  .vscode/tasks.json
Labels: enhancement

#45 Feat/lexical analyzer
  include/parse.h
  include/parse_util.h
  lib/libft/src/memory/ft_malloc.c
  src/parse/lexical_analyzer.c
  src/parse/parse.c
  src/parse/parse_exit.c
  src/parse/tokenizer.c
Labels: enhancement, parse

#47 fix: lexical_analyzer
  .vscode/launch.json
  .vscode/tasks.json
  include/parse_util.h
  src/parse/lexical_analyzer.c
  src/parse/tokenizer.c
Labels: parse
